//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTSDataManager.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConcertGroup
    {
        public int ConcertId { get; set; }
        public int GroupId { get; set; }
        public int ConcertGroupsId { get; set; }
    
        public virtual Concert Concert { get; set; }
        public virtual MusicGroup MusicGroup { get; set; }
    }
}
