//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTSDataManager.DB
{
    using System;
    
    public enum CustomerStatus : int
    {
        Buyed = 0,
        Reserved = 1
    }
}
